version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "concordnow/frontend"
    ignore:
      - dependency-name: ember-cli
        versions:
          - ">= 0"
      - dependency-name: ember-source
        versions:
          - ">= 0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "concordnow/frontend"
