---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "12"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint
        - npm run test:percy

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm run test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-lts-3.20
    - env: PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-release
    # - env: PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-beta
    # - env: PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-classic

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

deploy:
  provider: npm
  email: npmjs@concordnow.com
  api_key:
    secure: RgfileC02MGJ3Ff5sf5mNr9a198cHLiJZxAuqnYC8lj9QkTxPHk2HwzgjzXSm/059eLtFPTdKqwiffmFWf7WRCzOfI40o6A3XXAi1WkVlu07oOqAhLa+qnDYHN8E+7Xyn6d30jHEydGY/ogDF08rEo/Zjh/9v/GRiU/htmev20cKdAngkpGN/pA4Kch96Vab0hpdyfXeBRh0sV3xz0h9Yc0onrlPX+3wOfnjctJjpLcmLmPOciyzCGdIUr1TaR7lC/Ye9jzivVgOzwDcwDXOv2uqRGGM81++GgDPuVM4aQbA8i8eh6TUq7vChMFKlDi4DOxx6/+xISd10mLGmyrHdIYkxU3WyDFV4ECbguHVj5ovLx+Q0DD9e+V8yYBrqYxqhtCGdJZ4SnX+Igi1vPSBIR/vr7H1lCeS/s8V9ZAeWTqIuMU2Ihdz43eG/Ksws06yePG0VDaW/ygzIE4X7MDmOAbHLpLeeE0Vf2xx00/jtdDrj4WFE6wTjLqk4f0gdv0qh61lzaQ1DtJClX8bwAR8JYyyWJHvb09S2ll1Md7XHm5itcOeo76QoPpl3DUWwzYtQeO5KaKl4CkaM4sPACYjNv0p1w1yh0L/UHiH81LtN26j4MalXNdSvPIFP2JAUKYnGexIRFZO7F/CCujMpMjEQKokK9fF4dNZKTpAocqE3Gw=
  on:
    tags: true
    repo: concordnow/ember-content-loader
